pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                
              /*  mvn archetype:generate -DgroupId=io.stockgeeks \
                       -DartifactId=webproject-example \
                       -DarchetypeArtifactId=maven-archetype-webapp */
                
             /*   mvn archetype:generate -DgroupId=io.stockgeeks \
                       -DartifactId=my-app \
                       -DarchetypeArtifactId=maven-archetype-my-app */
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
                
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                 echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
            }
        }
        stage('Generate Artifact') {
                steps {
                    script {
                   def workspace = WORKSPACE
                   workspace = env.WORKSPACE
                    echo "Current workspace is ${env.WORKSPACE}"
                     echo "Current workspace is $WORKSPACE"
                        
                    // sha256sum = sh(returnStdout: true, script: "sha256sum '${fileName}'")

          /*          def checkScumTxt =httpRequest "http://10.148.0.6:8081/service/rest/v1/search/assets/download?repository=demo&sort=version&maven.groupId=com.web.net&maven.artifactId=web-Demo&maven.baseVersion=${params.projVersion}&maven.extension=tar.sha1&maven.classifier="
                    sh "echo '{ \"group\":\"com.web.net\"' > artifact.txt"
                    sh "echo ',\"checksum\":\"${checkScumTxt.content}\"' >> artifact.txt"
                    sh "echo ',\"artifact\":\"web-Demo\"' >> artifact.txt"
                    sh "echo ',\"database\":\"yes\"' >> artifact.txt"
                    sh "echo ',\"version\":\"${params.projVersion}\" }' >> artifact.txt"
                    */

                    }
                }
            }
    }
    
    post {
        always {
            archiveArtifacts artifacts: 'target/*.jar', fingerprint: true, onlyIfSuccessful: true
                }
    }
}
